Repository JNU-econovation/econo-sigma, pull requests merged in 2024-07, with the labels that each got.

#73 [FE/FIX] API 변경 요청 반영
  FE/admin_pages/src/App.js
  FE/admin_pages/src/components/common/Title.jsx
  FE/admin_pages/src/components/common/buttons/ApproveButton.jsx
  FE/admin_pages/src/components/common/buttons/delbutton.jsx
  FE/admin_pages/src/components/common/myPageCategory.jsx
  FE/admin_pages/src/components/common/tables/bookApproveTable.jsx
  FE/admin_pages/src/components/common/tables/bookTable.jsx
  FE/admin_pages/src/components/common/tables/userTable.jsx
  FE/user_pages/src/App.js
  FE/user_pages/src/components/common/Category.jsx
  FE/user_pages/src/components/common/Detail.jsx
  FE/user_pages/src/components/common/header/header.jsx
  FE/user_pages/src/components/common/header/logo.jsx
  FE/user_pages/src/components/common/home/SearchBar.jsx
  FE/user_pages/src/pages/book.jsx
  FE/user_pages/src/pages/main.jsx
Labels: FE

#84 [BE/FEAT] 도서 등록 요청, 도서 승인 api 추가
  BE/chackcheck/src/main/java/sigma/chackcheck/common/util/CategoryParser.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/BookController.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/domain/BookApprove.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/domain/BookCategory.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/domain/BookDetail.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/domain/BookRegister.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/request/CreateBookApproveRequest.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/request/CreateBookRequest.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/request/CreateBookRequestDTO.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/repository/BookRegisterRepository.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/repository/CategoryRepository.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/BookService.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/GetBook.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/PostBook.java
Labels: BE, feature

#94 [BE/FEAT] 모든 api에 /api 추가, 관리자 api에 /admin 추가
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/BookController.java
Labels: BE, feature

#98 [BE/FIX] SecurityContext에 인증객체 전송 및 응답
  BE/chackcheck/src/main/java/sigma/chackcheck/auth/controller/LoginSuccessJWTProvideHandler.java
  BE/chackcheck/src/main/java/sigma/chackcheck/auth/repository/RefreshTokenRepository.java
  BE/chackcheck/src/main/java/sigma/chackcheck/common/config/TokenAuthenticationFilter.java
  BE/chackcheck/src/main/java/sigma/chackcheck/common/config/WebSecurityConfig.java
  BE/chackcheck/src/main/java/sigma/chackcheck/common/config/jwt/TokenProvider.java
  BE/chackcheck/src/main/java/sigma/chackcheck/common/util/CookieUtil.java
Labels: BE, fix

#100 [BE/FEAT] 로그아웃 기능 구현
  BE/chackcheck/src/main/java/sigma/chackcheck/auth/controller/CustomLogoutHandler.java
  BE/chackcheck/src/main/java/sigma/chackcheck/auth/controller/CustomLogoutSuccessHandler.java
  BE/chackcheck/src/main/java/sigma/chackcheck/auth/controller/LoginSuccessJWTProvideHandler.java
  BE/chackcheck/src/main/java/sigma/chackcheck/common/config/TokenAuthenticationFilter.java
  BE/chackcheck/src/main/java/sigma/chackcheck/common/config/WebSecurityConfig.java
Labels: BE, feature

#101 [BE/FEAT] admin 인가 설정
  BE/chackcheck/src/main/java/sigma/chackcheck/auth/controller/LoginSuccessJWTProvideHandler.java
  BE/chackcheck/src/main/java/sigma/chackcheck/common/config/WebSecurityConfig.java
  BE/chackcheck/src/main/java/sigma/chackcheck/common/config/jwt/TokenProvider.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/domain/Role.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/domain/User.java
  BE/chackcheck/src/test/java/sigma/chackcheck/user/userTest.java
Labels: BE, feature

#96 feat:#95 회원 등록 페이지 구성
  FE/admin_pages/package-lock.json
  FE/admin_pages/package.json
  FE/admin_pages/src/App.js
  FE/admin_pages/src/components/common/Category.jsx
  FE/admin_pages/src/components/common/Title.jsx
  FE/admin_pages/src/pages/BookList.jsx
  FE/admin_pages/src/pages/RegisterMember.jsx
  FE/user_pages/src/App.js
  FE/user_pages/src/pages/RegisterMember.jsx
Labels: FE, feature

#106 [BE/REFACTOR] admin api 분리
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/BookController.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookController.java
Labels: BE, refactor

#108 [BE/FIX] 에러 해결
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java
Labels: BE, fix

#109 [BE/FEAT] 회원 정보 조회
  BE/chackcheck/src/main/java/sigma/chackcheck/auth/controller/LoginSuccessJWTProvideHandler.java
  BE/chackcheck/src/main/java/sigma/chackcheck/common/config/JsonUsernamePasswordAuthenticationFilter.java
  BE/chackcheck/src/main/java/sigma/chackcheck/common/config/WebSecurityConfig.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/controller/UserController.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/response/UserResponse.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/service/UserService.java
Labels: BE, feature

#111 [BE/FIX] CORS 해결
  BE/chackcheck/src/main/java/sigma/chackcheck/common/config/WebConfig.java
  BE/chackcheck/src/main/java/sigma/chackcheck/common/config/WebSecurityConfig.java
Labels: BE, fix

#113 [BE/FEAT] 도서 반납/대출 추가
  BE/chackcheck/src/main/java/sigma/chackcheck/auth/service/RefreshTokenService.java
  BE/chackcheck/src/main/java/sigma/chackcheck/auth/service/TokenService.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/BookController.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/domain/BookDetail.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/request/CreateBookApproveRequest.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/repository/BookCategoryRepository.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/BookService.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/GetBook.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/PostBook.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/controller/BookBorrowController.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/domain/BookBorrow.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/dto/response/BookBorrowResponse.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/repository/BookBorrowRepository.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/service/BookBorrowService.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/service/GetBookBorrow.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/service/PutBookBorrow.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/domain/User.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/service/UserDetailService.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/service/UserService.java
Labels: BE, feature

#114 [BE/FEAT] 대출 이력 조회
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/repository/BookBorrowRepository.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/controller/UserController.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/response/BookRentInfoResponse.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/response/BookRentInfosResponse.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/service/UserBorrowHistoryService.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/service/UserService.java
Labels: BE, feature

#116 [BE/FEAT] dueDate 추가
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/BookController.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/domain/BookBorrow.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/dto/response/BookBorrowDTO.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/service/PutBookBorrow.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/domain/User.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/request/AddUserRequest.java
Labels: BE, feature

#117 [BE/FEAT] 도서 정보 삭제 기능
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/BookController.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/domain/BookDetail.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/repository/BookDetailRepository.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/BookService.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/GetBook.java
Labels: BE, feature

#118 [BE/FEAT] 현재 대출 중인 도서 조회
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/repository/BookBorrowRepository.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/controller/UserController.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/response/BookRentInfoResponse.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/service/UserBorrowHistoryService.java
Labels: BE, feature

#120 [BE/FIX] 회원 등록
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/controller/UserController.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/domain/User.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/request/AddUserRequest.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/service/UserService.java
Labels: BE, fix

#121 [BE/FEAT] 추가 기능 구현
  BE/chackcheck/src/main/java/sigma/chackcheck/ChackcheckApplication.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/repository/BookRepository.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/BookService.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/GetBook.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/service/BookBorrowService.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/domain/Penalty.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/domain/User.java
Labels: BE, feature

#129 feat: .
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/BookInfoDTO.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/BookPageAdminResponse.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/repository/BookDetailRepository.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/BookService.java
Labels: BE, feature

#130 feat: 임시 코드
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/BookInfoDTO.java
Labels: BE, feature

#132 feat: 관리자 도서 관리 페이지
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/repository/BookCategoryRepository.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/BookService.java
Labels: BE, refactor

#137 [BE/FEAT] dto에 이미지 추가
  BE/chackcheck/src/main/java/sigma/chackcheck/S3/S3Service.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/BookApproveDTO.java
Labels: BE, feature

#138 [BE/FEAT] 원상태로 복구하면서 BookDto에 imageUrl 추가
  BE/chackcheck/src/main/java/sigma/chackcheck/S3/S3Service.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/BookApproveDTO.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/BookDTO.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/FullBookDTO.java
Labels: BE, feature

#139 [BE/FEAT] 유저 전체 조회 추가
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/response/CurruentBorrowedBook.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/response/CurruentBorrowedBooks.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/response/UserInfo.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/response/UserInfos.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/response/UserPageAdminResponse.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/repository/UserRepository.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/service/UserService.java
Labels: BE, feature

#140 refactor: uri 수정
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java
Labels: BE, refactor

#141 [BE/FEAT] 도서 승인 삭제 추가
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/BookService.java
Labels: BE, feature

#149 feat: BookApproveDTO 수정
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/BookApproveDTO.java
Labels: BE, feature

#150 feat: 소문자/대문자 해결
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/BookService.java
Labels: BE, fix

#152 feat: 회원 가입 수정
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/controller/UserController.java
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/service/UserService.java
Labels: BE, feature

#156 refactor: 도서 상세 정보 조회 dto 변경
  BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/FullBookDTO.java
Labels: BE, refactor
